# Generated by Django 5.2.14 on 2026-06-03 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_signature_height_document_signature_page_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='source',
            field=models.CharField(choices=[('web', 'Web'), ('api', 'API')], default='web', max_length=10),
        ),
        migrations.CreateModel(
            name='SignatureProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del perfil (ej: Escuela de Derechos)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Descripción o notas del perfil', null=True)),
                ('page', models.IntegerField(default=1, help_text='Página donde se aplicará la firma (inicia en 1)')),
                ('x', models.FloatField(help_text='Coordenada X en puntos PDF')),
                ('y', models.FloatField(help_text='Coordenada Y en puntos PDF')),
                ('width', models.FloatField(default=200, help_text='Ancho de la firma en puntos')),
                ('height', models.FloatField(default=50, help_text='Alto de la firma en puntos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SignatureBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('web', 'Web'), ('api', 'API')], default='web', max_length=10)),
                ('document_count', models.IntegerField(help_text='Cantidad de documentos firmados en este lote')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_batches', to=settings.AUTH_USER_MODEL)),
                ('signature_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.signatureprofile')),
            ],
        ),
    ]
